name: publish snapshot

on:
  push:
    branches:
      - 'snapshot/*'


jobs:
  publish:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      - name: Install automake
        if: matrix.os == 'macOS-latest'
        run: brew install automake
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Check
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: check --no-daemon
      - name: Get snapshot name
        id: snapshot_extract
        run: echo ::set-output name=NAME::${GITHUB_REF#refs/heads/snapshot/}
      - name: Publish
        uses: eskatos/gradle-command-action@v1
        env:
          BINTRAY_USER: ${{ secrets.bintray_user }}
          BINTRAY_APIKEY: ${{ secrets.bintray_apikey }}
        with:
          arguments: publish -PsnapshotName=${{ steps.snapshot_extract.outputs.NAME }} -PsnapshotNumber=${{ github.run_number }}